const prettier = require('eslint-config-prettier');

module.exports = [
  {
    ignores: ['dist/', 'node_modules/', 'src/renderer/assets/fonts/'],
  },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        fetch: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setImmediate: 'readonly',
        AudioContext: 'readonly',
        location: 'readonly',
        URL: 'readonly',
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Blob: 'readonly',
        Image: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        IntersectionObserver: 'readonly',
        global: 'readonly',
        __seaxDjInactive: 'writable',
        __seaxUserPaused: 'writable',
        _seaxUserVolume: 'writable',
        seaxAudioCtx: 'writable',
        seaxAnalyser: 'writable',
        seaxAudioSource: 'writable',
        seaxDataArray: 'writable',
        seaxVisualizerInterval: 'writable',
        seaxPreviousData: 'writable',
        lastVideoPausedState: 'writable',
        lastRepeatTriggered: 'writable',
        videoEndedNotified: 'writable',
        repeatCooldown: 'writable',
        repeatMode: 'writable',
        shuffleMode: 'writable',
        ipcRenderer: 'readonly',
        contextBridge: 'readonly',
        desktopCapturer: 'readonly',
        ImageData: 'readonly',
        HTMLVideoElement: 'readonly',
        MediaRecorder: 'readonly',
        MouseEvent: 'readonly',
        AudioContext: 'readonly',
        webkitAudioContext: 'readonly',
        globalThis: 'readonly',
        isLoggedIn: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^e' }],
      'no-console': 'off',
      'no-undef': 'off',
      'prefer-const': 'warn',
      'no-var': 'warn',
      'eqeqeq': ['warn', 'always'],
      'no-prototype-builtins': 'off',
    },
  },
  prettier,
];
